# tasks/main.yml
---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required dependencies
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-venv
      - python3-dev
      - build-essential
    state: present

- name: Create the application directory
  ansible.builtin.file:
    path: "{{ flask_app_directory }}"
    state: directory
    owner: "{{ flask_app_user }}"
    group: "{{ flask_app_group }}"
    
- name: Copy requirements.txt to the application directory
  ansible.builtin.copy:
    src: "requirements.txt"
    dest: "{{ flask_app_directory }}/requirements.txt"
    owner: "{{ flask_app_user }}"
    group: "{{ flask_app_group }}"
- name: Create virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv {{ flask_venv }}
    creates: "{{ flask_venv }}/bin/activate"

- name: Install Flask and Gunicorn in the virtual environment
  ansible.builtin.pip:
    requirements: "{{ flask_app_directory }}/requirements.txt"
    virtualenv: "{{ flask_venv }}"

- name: Deploy Flask app
  ansible.builtin.copy:
    src: "files/app.py"
    dest: "{{ flask_app_directory }}/{{ flask_app_file }}"
    owner: "{{ flask_app_user }}"
    group: "{{ flask_app_group }}"

- name: Create Gunicorn systemd service
  ansible.builtin.template:
    src: "flaskapp.service.j2"
    dest: "/etc/systemd/system/{{ flask_app_name }}.service"
    mode: '0644'

- name: Reload systemd to recognize the new service
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start Gunicorn service
  ansible.builtin.systemd:
    name: "{{ flask_app_name }}.service"
    state: started
    enabled: yes
