---

- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy index.html using Jinja2 template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    - restart nginx

- name: Ensure NGINX is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes

